### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by kangalio** [kyleedwardsny/bergen#1]
Can you please tell me (or put it in your README) how I can compile your code? I am not that much of a C pro so I am not able to think of the required commands myself. Thanks!

**Comment by kyleedwardsny** [comment]
Hi kangalioo,

I haven't worked on this project in years, and it is *extremely* incomplete - not in anything resembling a usable state.

That said, it builds using the SCons buildsystem. However, if I was to pick this up again, I would rewrite the build scripts with CMake instead.

**Comment by kangalio** [comment]
Ok, thanks anyway.

For future visitors: You can try [zasm](https://k1.spdns.de/Develop/Projects/zasm/Distributions/). It's actively developed and has many useful features, e.g. including C files
